### ISSUE TITLE
[Scene Datasets] Request for a copy of scene datasets on cloud disk

### ISSUE THREAD

**Issue by A-Nobel** [XinyuSun/FGPrompt#1]
Hello, sorry to bother you~

**Comment by A-Nobel** [comment]
I am very interested in your work and was hoping you would be willing to also share a link to the scene dataset on cloud disk. Cause it is difficult to download the three huge scene datasets.😹 I would greatly appreciate being able to access the cloud disk link. Thank you very much for your consideration of my request.😸

**Comment by XinyuSun** [comment]
sure, my wechat ID is Anthracenesy
