### ISSUE TITLE
scene dataset

### ISSUE THREAD

**Issue by 21stYouth** [XinyuSun/FGPrompt#3]
Hello, I have some problem in downloading Scene Datasets. I would be grateful if you can copy the cloud dist.

**Comment by XinyuSun** [comment]
Hi! I can not directly share a copy on the GiuHub as it breaks the license. If you still have problems downloading them, feel free to contact me through email csxinyusun@gmail.com or wechat (see [previous issue](https://github.com/XinyuSun/FGPrompt/issues/1#issuecomment-1811589552)).
