### ISSUE TITLE
Downloading and advice

### ISSUE THREAD

**Issue by zhoubohan0** [XinyuSun/FGPrompt#4]
Nice work, easy to follow! Could you please share a copy to help download scene files? And could you also provide some details for reimplementing the experiments? Thanks a lot.

**Comment by XinyuSun** [comment]
Hi! We have provided the training code and evaluation code for re-implementation. We recommend you evaluate our released model following the commands in the [readme](https://github.com/XinyuSun/FGPrompt?tab=readme-ov-file#41-download-the-trained-model-to-reproduce-the-results-%EF%B8%8F), and then train your model following [commands](https://github.com/XinyuSun/FGPrompt?tab=readme-ov-file#3-run-imagenav-training-)!  But you should prepare for the scene datasets first. If you find it hard to download the scene dataset, please contact me on WeChat (ID: Anthracenesy) and I'll share a copy with you using the cloud disk.
